### ISSUE TITLE
minor fixes to allow appredict to be compilled with c++11 and pycml

### ISSUE THREAD

**Issue by martinjrobins** [Chaste/ApPredict#16]
It would be nice that ApPredict still work with older installations of chaste that are still using c++11 and pycml, I would like to make the following changes if there are no objections?

```
diff --git a/SConscript b/SConscript
index e111a1d..e7125c8 100644
--- a/SConscript
+++ b/SConscript
@@ -48,6 +48,9 @@ chaste_libs_used = ['heart']
 # Change some flags just for this project
 env = SConsTools.CloneEnv(env)
 env['Chaste_CODEGEN_EXTRA_ARGS'] = ['--use-model-factory']
+env['PYCML_EXTRA_ARGS'] = ['--expose-annotated-variables']
+
+

 # Do the build magic
 result = SConsTools.DoProjectSConscript(project_name, chaste_libs_used, globals())
diff --git a/src/fortests/ModelFactory.cpp b/src/fortests/ModelFactory.cpp
index 02a3e2f..2b90129 100644
--- a/src/fortests/ModelFactory.cpp
+++ b/src/fortests/ModelFactory.cpp
@@ -41,7 +41,7 @@ ModelFactory::TModelMapping ModelFactory::getModelRegistry()
 {
     if (ModelFactory::mpModelRegistry == nullptr)
     {
-        ModelFactory::mpModelRegistry = std::make_unique<std::map<std::pair<std::string, std::string>, ModelFactory::TCreateMethod>>();
+        ModelFactory::mpModelRegistry = std::make_shared<std::map<std::pair<std::string, std::string>, ModelFactory::TCreateMethod> >();
     }
     return ModelFactory::mpModelRegistry;
 }
```

**Comment by mirams** [comment]
Dunno if there is a reason for preferring unique over shared pointer here @MauriceHendrix, if there is we could probably use the boost version like we used to do with shared_ptr on C++98.

**Comment by martinjrobins** [comment]
`ModelFactory::mpModelRegistry` was already a `std::shared_ptr`, I wasn't sure why the line makes a `std::unique_ptr`...?

**Comment by martinjrobins** [comment]
@MauriceHendrix, let me know if you think this change is ok. I'm easy either way, I'm currently just patching the source before we install, but obviously its easier in the long run if the change is made. Saying that, I don't want to hold back Chaste moving up the C++ version chain (shoutout to @fcooper8472 here)!!

**Comment by MauriceHendrix** [comment]
> It would be nice that ApPredict still work with older installations of chaste that are still using c++11 and pycml, I would like to make the following changes if there are no objections?

I think I used unique more just to check that my understanding of where it's accessed and refered to was correct. There shouldn't really be any problem making it a shared pointer.

as for re-introducing `PYCML_EXTRA_ARGS` I'd be a little bit concerned that this as a variable doesn't make a whole lot of sense for the rest of Chaste. Also: @martinjrobins are you intending to run this on an older OS? PyCml needs Python 2 and since the last couple of Ubuntu releases don't come with Python2 by default anymore. I've found it's getting increasingly tricky to get it going. Is there a lot of things that codegen gives you problems with when compiling as C+11?

**Comment by martinjrobins** [comment]
Yes, it is an older OS that doesn't have a C++14 compiler, so we are using an older version of chaste that is restricted to c++11. This older version also uses pycml. The codegen seems to work ok though, as long as I make the changes above and wind back the version of the cellml submodule

**Comment by MauriceHendrix** [comment]
Why do you need to wind back the version of the CellML submodule? Is it that certain tests fail without that (which would make sense) or something else going on?

**Comment by martinjrobins** [comment]
There was an pycml error, something about a variable(?) not being found (oxmeta), which went away when I wound it back. I can look into it more if you think it is important?

**Comment by MauriceHendrix** [comment]
aah that could be the version of the ontology maybe ... not sure.

**Comment by MauriceHendrix** [comment]
so in short: I don't mind about the pointer (unique/shared) not completley sure about `PYCML_EXTRA_ARGS`, I mean I don't mind but might come acreoss a bit messy, what do you think @mirams ?

**Comment by mirams** [comment]
Presumably you've tested this @martinjrobins ? Are all the Chaste and ApPredict tests passing? 

I will admit to being a bit confused, I thought that core Chaste relied on python3 being around now, and made no mention of PyCML anymore, or are you managing to get the current ApPredict building with an old Chaste? (if so that is working mainly by luck and lack of changes to core cardiac Chaste API, which can't be guaranteed to continue!).

So apart from that, I am also getting nervous about giving people an ApPredict that might be half-working, for the following reasons:
 * If it relies on an obselete ontology: the annotation tool in the WebLab will use the most up to date one and potentially put in tags that a PyCML-ApPredict can't use but everyone else's can. Feels like a recipe for hard to track down bugs!

 * Since PyCML will ignore the `env['Chaste_CODEGEN_EXTRA_ARGS'] = ['--use-model-factory']` line above, presumably the model factory will no longer work, so I would be surprised if all ApPredict tests pass, but perhaps you can still build it and use hardcoded models?

 * Also I was about to finally delete the scons option, because Maurice is about to make changes to the core Chaste that will rely on using cmake to build Chaste. So you won't be able to run a passing full suite of Chaste & ApPredict tests with any scons build after that. 

So I would strongly suggest to try and move to using the latest ApPredict dockerhub thing rather than bake in at least 3 un-ideal things!

**Comment by martinjrobins** [comment]
nope, I've just been following the apportal installation scripts, which don't (?) seem to run tests, it just builds the app: https://bitbucket.org/gef_work/ap_predict_online/src/master/tools/ApPredict/install/x86_64/CentOS/6.5/minimal/2chaste/1build.sh

I'll have a go at running tests and get back to you

totally agree with being nervous about upgrading ApPredict while still keeping the old version of chaste, my original plan was to keep the existing versions, but you then encouraged me to use the newer ApPredict version instead so I went down that route.

Note this is only a temporary step to enable the incorporation of a new cellml and so I can become familiar with the setup. I think using the dockerised ApPredict is a sensible next step

**Comment by martinjrobins** [comment]
so, loads of errors. Am thinking of forking the old guinea pig branch and adding new cellml model from that, probably easier than getting new appredict to work with old chaste. So can close this if you want
