### ISSUE TITLE
Rename master->main

### ISSUE THREAD

**Issue by mirams** [Chaste/ApPredict#27]
Would just do this, but probably will break the github actions?

**Comment by mirams** [comment]
Pinged you @kwabenantim to think about that, and then we can update the docker build stuff at the same time.

**Comment by fcooper8472** [comment]
We should check the following things before pressing the button:

- GitHub actions workflows
- Interaction with the git repo that is still receiving updates on chaste.cs
- Documentation

**Comment by kwabenantim** [comment]
I'll have a look through these and set up a PR @mirams @fcooper8472

**Comment by kwabenantim** [comment]
**Will need updating**
- Github actions on [ApPredict](https://github.com/Chaste/ApPredict)

**May need updating**
According to the [guidance](https://github.com/github/renaming), GitHub will redirect links from the old branch name to the new one.
- AP Nimbus documentation and comments:
  - [Updating ApPredict](https://ap-nimbus.readthedocs.io/en/latest/developer/updating-appredict/index.html?highlight=master#updating-appredict)
  - https://github.com/CardiacModelling/ap-nimbus-app-manager/blob/master/run_me.sh#L65

**Won't need updating**
- The [appredict-docker images](https://github.com/CardiacModelling/appredict-docker) don't specify a branch name so I think those should be fine.
- On trac, the last commit message for project ApPredict 7 years ago says "closing down SVN repo and moving to Github" so that should be fine as well.

**Comment by kwabenantim** [comment]
![image](https://github.com/Chaste/ApPredict/assets/1944963/a13c7e5c-88d7-4642-bf86-bb32be0629f1)

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by kwabenantim** [comment]
I've confirmed that old links now get redirected to the new branch e.g. https://github.com/Chaste/ApPredict/blob/master/src/lookup/LookupTableLoader.cpp
